module.exports.categories = [
    'Italian',
    'Greek',
    'French',
    'Chinese',
    'Mexican',
    'American',
    'Turkish',
    'Street food'
]

module.exports.descriptions = [
    "A little more than a decade ago, my cousin - an Italian cook - took me along to visit his restaurant in the countryside.  My first taste of Italian food was in this cozy, dark, wood-panelled room.  I was hooked.  I haven't been able to forget",
    "Souvlaki of lamb, pork, chicken, or seafood are some popular Greek dishes that we have in our restaurant. The souvlaki is the name for the small, spit-roasted meat patties. We have authentic greek recipes by our greek chef.",
    "Eating authentic, Parisian-style dining in Greece is easier than you think. Our menu is filled with tasty dishes that will transport you to France.",
    "Known for its many dishes, and its long wait times, our Chinese restaurant is the perfect place to go when you're looking for something to eat. This restaurant is a place where you can find all the traditional dishes that you would find at a Chinese restaurant like sushi, bao buns and noodles.",
    "You won't find Tex-Mex here. This place is pure Mexican food, from the authentic enchiladas to the puffy tacos and even the tamales. They offer a variety of meats, seafood, and vegetables to create a complete Mexican experience.",
    "Our Restaurant is the perfect place for a family gathering or a romantic date. It offers a wide variety of american food from burgers to salads and sandwiches. The restaurant also has a number of signature dishes like the Greek salad, the garlic shrimp, and the steak and cheese burger.",
    "Our Turkish restaurant in Greece is a family owned business that offers the best in Turkish cuisine. You'll enjoy our variety of salads, kabobs, and of course, our amazing baklava. Our delicious food is served with fresh lemon and our delicious Turkish coffee.",
    "What’s not to love about a street food restaurant? If you love eating authentic, tasty and inexpensive food, this is the place for you."
]

module.exports.names = [
    "16 Handles",
    "Franktuary",
    "Lettuce Eat",
    "Like No Udder",
    "Cheesy Does It",
    "Turnip The Beat",
    "Lattetude",
    "Sea You Soon",
    "Burgatory",
    "Unphogettable",
    "Dairy Godmother",
    "Meat U There",
    "Eats Meets West",
    "Egglectic Café",
    "Sun of a Bun",
    "Basic Kneads Pizza",
    "21 & Cup",
    "Moon Wok",
    "Fry the Coop",
    "Drink and Dive",
    "Garden of Eat’n",
    "Eat Your Heart Out",
    "Holy Mole",
    "Kale Me Crazy",
    "Thai & Mighty",
    "Brewed Awakening ",
    "Lets Ketchup",
    "Nacho Daddy",
    "The Brewseum",
    "Award Wieners",
    "Jamaica Mi Krazy",
    "Party Fowl",
    "No Name Restaurant ",
    "Killer Pizza from Mars",
    "The French Laundry",
    "Starbelly",
    "Egg Slut",
    "Goosefoot",
    "Garage Kitchen + Bar",
    "Mr. & Mrs. Bun",
    "Six Seven",
    "Gochew Grill",
    "Zero Zero",
    "Girl and the Goat",
    "Odd Duck",
    "Toro Toro",
    "The Purple Pig",
    "Bite Me Sandwiches",
    "The Pink Door",
    "Blue Mermaid",
    "Pies N’ Thighs",
    "Backyard Bowls",
    "Mellow Mushroom",
    "Wicked Wok",
    "Pie In the Sky",
    "Chops and Hops",
    "Yummy In The Tummy",
    "Slice of Spice",
    "Pig’N Pancake",
    "Late Night Dine Right",
    "Chops & Hops",
    "Blazing Bean Roasters",
    "Overflowing Soy",
    "Rockin’ and Ramen",
    "Wen Do We Eat",
    "Good Luck and Peking Duck",
    "Lost in China Buffet",
    "Year of Delicious",
    "Yin and Yummy",
    "The Zen Garden",
    "Sesame World",
    "The Efficient Panda",
    "Chop Chop Restaurant",
    "Pow Pow",
    "Seaweed and Soy",
    "Chinese Culinary Graduate",
    "Poke Toki",
    "Ichigo Ichie",
    "Wasabi",
    "Bamboo House",
    "Dreamcatcher",
    "Simple Fish",
    "Thai Tanic",
    "Nom Nom Wok",
    "Thai the Knot",
    "Bangkok Belly",
    "Thai Me Up",
    "Weera Thai Restaurant",
    "En Thai Sing",
    "Coconut Garden",
    "Mamma In Cucina",
    "Tommy Guns Garage",
    "L’ultima Cena ",
    "Bella Bella Mozzarella",
    "Sapori D’Italia ",
    "Pane e Vino",
    "P’sghetti’s",
    "The Saucy Meatball",
    "L’unico ",
    "The Tasty Tortellini",
    "Juan in a Million",
    "Taco ‘Bout It",
    "Uno Mas Taquiza",
    "One Taco Dos Tequilas",
    "Guacamole Brothers",
    "Burrito Bandidos",
    "Local Lime",
    "The Little Chihuahuha",
    "Burrito Boyz",
    "Taco Town",
    "El Speedy Gonzalez",
    "Tikkaway",
    "Curry Kingdom",
    "Tikka ‘n’ Talk",
    "The Spice Factory",
    "The Paneer Bar",
    "Curry Leaves",
    "The Naan House",
    "Mr. Tandoor",
    "The Flying Carpet",
    "Once Upon a Flame",
    "Curry Kitchen",
    "Punjab Paradise",
    "Taste of Bavaria",
    "Alter Haferkasten",
    "Bavarian Inn Restaurant",
    "Frühsammers",
    "Lebkuchen Star",
    "Wunderbar",
    "Jägerhaus",
    "World of Wurst",
    "Rasta Pasta",
    "Irie Kitchen",
    "Yamon Jerk Grill",
    "Jamaican Jerk King",
    "Jamaican Me Hungry",
    "Just Jerks",
    "Caribbean Cove",
    "Island Vibez",
    "Big Jerk",
    "Just Falafs",
    "Pegasus Taverna",
    "Mr Greek Gyros",
    "Zeus Restaurant",
    "Pita Heaven",
    "Hummus Grill",
    "Shawarma Garden",
    "Ocean Breeze Restaurant",
    "Queen of Sheba Ethiopian Restaurant",
    "Nando’s Peri-Peri",
    "Kiza",
    "Blue Nile Ethiopian Restaurant",
    "Nefertiti Restaurant",
    "Arabian Nights",
    "Hummus Genie",
    "The Palm Oven",
    "Hummus House",
    "The Lion of the Nile",
    "Saffron Palace",
    "Olives & Figs",
    "Bazaar Falafel",
    "Pot Au Feu",
    "The Aviary",
    "Brass Tacks",
    "Cibo Matto",
    "Catch 35",
    "Parallel 37",
    "Eleven Madison Park",
    "Whataburger",
    "Fry Nation",
    "Project Pollo",
    "Pizza Pit",
    "Plant Power Fast Food",
    "The Burger Lab",
    "Arctic Circle",
    "Wok to Walk",
    "Steak ‘n Shake",
    "Just After Breakfast",
    "The City Of Brunch",
    "Toast Conference",
    "The Brunch Daddy",
    "Eggstravaganza",
    "Pass The Brunch",
    "The Brunch Branch",
    "Mister Toasty",
    "Brunch Munch",
    "The Early Lunch",
    "Hungry Brunch",
    "Hash Brown Camp",
    "Quiche Carnival",
    "Cereal Killer Café",
    "Before Lunch",
    "The A.M. Chow",
    "Mystery Brunch",
    "Hungry Brunch Bunny",
    "Rise n’ Dine",
    "Brunch Bowl",
    "Brunch Babes",
    "Morning Crumbs",
    "Of Rice & Men",
    "The Codfather",
    "The Breakfast Club",
    "Custard’s Last Stand ",
    "Happy Grillmore",
    "Lord of the Fried",
    "Café Jack",
    "Life of Pie",
    "The Hot and the Furious",
    "Filled of Dreams",
    "Lord of the Wings",
    "Eat Pray Love",
    "Frying Nemo",
    "Grillenium Falcon ",
    "Pita Pan",
    "Earth, Wind and Flour",
    "Wok This Way",
    "The Notorious P.I.G.",
    "Planet of the Grapes",
    "License To Grill",
    "Men At Wok"
]