module.exports = [
    "Acharnes",
    "Aegina",
    "Afidnes",
    "Agia Marina",
    "Agia Paraskevi",
    "Agia Varvara",
    "Agios Panteleimon",
    "Agios Dimitrios Kropias",
    "Agios Dimitrios",
    "Agios Ioannis Rentis",
    "Aianteio",
    "Ampelakia",
    "Anavyssos",
    "Anoixi",
    "Anthousa",
    "Argithea",
    "Argyroupoli",
    "Artemida",
    "Aspropyrgos",
    "Athens",
    "Avlonas",
    "Agioi Anargyroi",
    "Agios Stefanos",
    "Alimos",
    "Ano Liosia",
    "Agioi Apostoloi",
    "Ilion",
    "Ydra",
    "Chaïdari",
    "Cholargos",
    "Dhafni",
    "Dhrafi",
    "Dioni",
    "Dionysos",
    "Drapetsona",
    "Drosia",
    "Ekali",
    "Elefsina",
    "Elliniko",
    "Erythres",
    "Filothei",
    "Fyli",
    "Galatas",
    "Galatsi",
    "Gerakas",
    "Glyfada",
    "Grammatiko",
    "Ilioupoli",
    "Irakleio",
    "Kaisariani",
    "Kaisariani",
    "Kaisariani",
    "Kalyvia Thorikou",
    "Kallithea",
    "Kamateron",
    "Kapandriti",
    "Karellas",
    "Kalamos",
    "Kato Soulion",
    "Kitsi",
    "Kythira",
    "Keratea",
    "Keratsini",
    "Khalandrion",
    "Khalkoutsion",
    "Kifisia",
    "Kineta",
    "Kipseli",
    "Koropi",
    "Korydallos",
    "Kouvaras",
    "Kryoneri",
    "Kypseli",
    "Lavrio",
    "Leondarion",
    "Limin Mesoyaias",
    "Lykovrysi",
    "Magoula",
    "Marathonas",
    "Markopoulo",
    "Markopoulo Oropou",
    "Marousi",
    "Mandra",
    "Megara",
    "Megalochori",
    "Melissia",
    "Metamorfosi",
    "Moskhaton",
    "Nea Chalkidona",
    "Nea Erythraia",
    "Nea Filadelfeia",
    "Nea Ionia",
    "Nea Makri",
    "Nea Palatia",
    "Nea Peramos",
    "Nea Penteli",
    "Nea Smyrni",
    "Neo Psychiko",
    "Nikaia",
    "Neos Voutzas",
    "Oropos",
    "Paiania",
    "Palaia Fokaia",
    "Palaio Faliro",
    "Pallini",
    "Papagou",
    "Pefki",
    "Perama",
    "Poros",
    "Penteli",
    "Peristeri",
    "Petroupolis",
    "Pikermi",
    "Piraeus",
    "Polydendri",
    "Psychiko",
    "Rafina",
    "Rodopoli",
    "Salamina",
    "Saronida",
    "Selinia",
    "Skarmagkas",
    "Skala Oropou",
    "Spata",
    "Spetses",
    "Stamata",
    "Tavros",
    "Thrakomakedones",
    "Varnavas",
    "Varybobi",
    "Vathy",
    "Vari",
    "Vilia",
    "Vyronas",
    "Vlychada",
    "Voula",
    "Vouliagmeni",
    "Vrana",
    "Vrilissia",
    "Ymittos",
    "Zefyri",
    "Zografos"
]